/**
 * Converts a classification result into a human-readable explanation.
 * 
 * PURE LOGIC. No side effects. No filesystem access.
 * 
 * @param {object} classificationResult - { category, confidence }
 * @returns {object} - { title, explanation, riskLevel }
 */
function explainClassification(classificationResult) {
    // strict input contract: treat as read-only
    // safe default if input is missing
    const category = classificationResult?.category || 'unclassified';
    const confidence = classificationResult?.confidence || 'low';

    let title = 'Unknown Data';
    let explanation = '';
    // Risk levels: "low" | "normal" | "medium" | "user" | "unknown"
    let riskLevel = 'unknown';

    switch (category) {
        case 'logs':
            title = 'System Logs';
            explanation = 'Logs are generated by system services. They can grow over time due to activity.';
            riskLevel = 'normal';
            break;

        case 'cache':
            title = 'Cached Data';
            explanation = 'Cache is temporary data used to improve performance. It is usually regenerated automatically.';
            riskLevel = 'low';
            break;

        case 'containers':
            title = 'Container Data';
            explanation = 'Container images, layers, and volumes consume disk space. Unused images may accumulate.';
            riskLevel = 'medium';
            break;

        case 'packages':
            title = 'Package Data';
            explanation = 'Package managers may store multiple versions or snapshots.';
            riskLevel = 'low';
            break;

        case 'kernels':
            title = 'Kernel Files';
            explanation = 'Kernel images remain after system updates. Older kernels may still be present.';
            riskLevel = 'medium';
            break;

        case 'system':
            title = 'System Files';
            explanation = 'This is core operating system data. Modifying it may affect system stability.';
            riskLevel = 'normal';
            break;

        case 'user-data':
            title = 'User Data';
            explanation = 'This is data created or owned by the user.';
            riskLevel = 'user';
            break;

        case 'unclassified':
        default:
            title = 'Unrecognized Data';
            explanation = 'The data does not match known Linux patterns.';
            riskLevel = 'unknown';
            break;
    }

    // CONFIDENCE HANDLING
    if (confidence === 'low') {
        explanation += ' Classification is uncertain.';
    } else if (confidence === 'medium') {
        // We can prepend "This may be..." or generally use softer language. 
        // The requirement says "Use cautious language ('may', 'often')".
        // For simplicity and determinism, we can append a note or slightly adjust phrasing.
        // However, the base explanations above are already quite factual.
        // Let's prepend "This appears to be..." for strict adherence?
        // Actually, the simplest way is to just leave it as is if the base text is safe, 
        // OR prepend "Likely: " to the explanation.
        // Let's stick to the prompt's tone. The prompts explanations like "Logs are generated..." are factual.
        // If confidence is medium, we might add: " This identification is likely correct but not definite."
        // OR simpler:
        explanation = 'Likely: ' + explanation;
    }

    return {
        title,
        explanation,
        riskLevel
    };
}

module.exports = { explainClassification };
