const { explainClassification } = require('../src/intelligence/explainer');

function runTest(name, input, expectedContext) {
    const result = explainClassification(input);

    // Check strict equality for critical fields if exact match expected, 
    // or checks inclusion for explanation text.

    const titleMatch = result.title === expectedContext.title;
    const riskMatch = result.riskLevel === expectedContext.riskLevel;
    const explContains = result.explanation.includes(expectedContext.explanationSnippet);

    if (titleMatch && riskMatch && explContains) {
        console.log(`✅ ${name}: [${input.category} / ${input.confidence}] -> "${result.title}" (${result.riskLevel})`);
    } else {
        console.error(`❌ ${name}: [${input.category} / ${input.confidence}]`);
        console.error(`   Expected: Title="${expectedContext.title}", Risk="${expectedContext.riskLevel}", Text~="${expectedContext.explanationSnippet}"`);
        console.error(`   Got:      Title="${result.title}", Risk="${result.riskLevel}", Text="${result.explanation}"`);
        process.exitCode = 1;
    }
}

console.log('--- Testing Explainer Rules ---\n');

// 1. Logs
runTest('Logs (High)',
    { category: 'logs', confidence: 'high' },
    { title: 'System Logs', riskLevel: 'normal', explanationSnippet: 'generated by system services' }
);

// 2. Cache
runTest('Cache (High)',
    { category: 'cache', confidence: 'high' },
    { title: 'Cached Data', riskLevel: 'low', explanationSnippet: 'temporary data' }
);

// 3. Containers
runTest('Containers (High)',
    { category: 'containers', confidence: 'high' },
    { title: 'Container Data', riskLevel: 'medium', explanationSnippet: 'Container images' }
);

// 4. Packages
runTest('Packages (High)',
    { category: 'packages', confidence: 'high' },
    { title: 'Package Data', riskLevel: 'low', explanationSnippet: 'Package managers' }
);

// 5. Kernels
runTest('Kernels (High)',
    { category: 'kernels', confidence: 'high' },
    { title: 'Kernel Files', riskLevel: 'medium', explanationSnippet: 'Kernel images remain' }
);

// 6. System
runTest('System (High)',
    { category: 'system', confidence: 'high' },
    { title: 'System Files', riskLevel: 'normal', explanationSnippet: 'core operating system data' }
);

// 7. User Data
runTest('User Data (High)',
    { category: 'user-data', confidence: 'high' },
    { title: 'User Data', riskLevel: 'user', explanationSnippet: 'owned by the user' }
);

// 8. Unclassified
runTest('Unclassified (Low)',
    { category: 'unclassified', confidence: 'low' },
    { title: 'Unrecognized Data', riskLevel: 'unknown', explanationSnippet: 'does not match known Linux patterns. Classification is uncertain.' }
);

// Confidence variants
runTest('Logs (Medium)',
    { category: 'logs', confidence: 'medium' },
    { title: 'System Logs', riskLevel: 'normal', explanationSnippet: 'Likely: Logs are generated' }
);

runTest('System (Low)',
    { category: 'system', confidence: 'low' },
    { title: 'System Files', riskLevel: 'normal', explanationSnippet: 'Classification is uncertain.' }
);

console.log('\n--- Tests Complete ---');
